type Mutation {
  login(
    email: String!
    password: String!
  ): LoginOutput
}

type Mutation {
  pay(
    amount: String!
    email: String!
    first_name: String!
    last_name: String!
  ): PaymentOutput
}

type Mutation {
  signup(
    full_name: String!
    email: String!
    password: String!
  ): SignupOutput
}

type Mutation {
  upload_file(
    base64_data: String!
    filename: String!
  ): FileUploadOutput
}

type LoginOutput {
  token: String!
  id: String!
  full_name: String!
}

type SignupOutput {
  id: String!
  full_name: String!
  email: String!
}

type PaymentOutput {
  checkout_url: String!
  tx_ref: String!
}

type FileUploadOutput {
  url: String!
}

