type Mutation {
  login(
    email: String!
    password: String!
  ): LoginOutput
}

type Mutation {
  pay(
    schedule_id: String!
    seat_ids: [String!]!
    email: String!
    first_name: String!
    last_name: String!
  ): PaymentOutput
}

type Mutation {
  verify_payment(
    tx_ref: String!
  ): VerifyPaymentOutput
}

type Mutation {
  signup(
    full_name: String!
    email: String!
    password: String!
  ): SignupOutput
}

type Mutation {
  get_upload_signature: UploadSignatureOutput
}

type LoginOutput {
  token: String!
  id: String!
  full_name: String!
}

type SignupOutput {
  id: String!
  full_name: String!
  email: String!
}

type PaymentOutput {
  checkout_url: String!
  tx_ref: String!
}

type VerifyPaymentOutput {
  status: String!
  booking_reference: String!
  total_price: String!
  movie_title: String!
  start_time: String!
  full_name: String!
  seats: [String!]!
}

type UploadSignatureOutput {
  signature: String!
  timestamp: Int!
  api_key: String!
  cloud_name: String!
  folder: String!
}

